language: node_js
node_js:
  - "8.11"

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
     - node_modules

script:
  - ng lint
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng e2e --protractor-config=./e2e/protractor-ci.conf.js
  - ng build --prod
  - git rm -f package-lock.json

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    all_branches: true
  token:
    secure: $FIREBASE_TOKEN