language: node_js
node_js:
  - "8.11"

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
     - node_modules

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod
  - rm package-lock.json
  #- npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  #- npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

deploy:
  provider: firebase
  token:
    all_branches: true
    secure: $FIREBASE_TOKEN